version: "3"

services:
  sqs-local:
    image: roribio16/alpine-sqs:latest
    container_name: sqs_local
    ports:
    - 9324:9324
    - 9325:9325
    volumes:
    - ./custom/custom.conf:/opt/custom/elasticmq.conf
     
